// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Barbero struct {
	IDBarbero    int32          `json:"id_barbero"`
	Nombre       string         `json:"nombre"`
	Apellido     string         `json:"apellido"`
	Especialidad sql.NullString `json:"especialidad"`
}

type Cliente struct {
	IDCliente int32          `json:"id_cliente"`
	Nombre    string         `json:"nombre"`
	Apellido  string         `json:"apellido"`
	Telefono  sql.NullString `json:"telefono"`
	Email     sql.NullString `json:"email"`
}

type Turno struct {
	IDTurno       int32          `json:"id_turno"`
	IDCliente     int32          `json:"id_cliente"`
	IDBarbero     int32          `json:"id_barbero"`
	Fechahora     time.Time      `json:"fechahora"`
	Servicio      string         `json:"servicio"`
	Observaciones sql.NullString `json:"observaciones"`
}
