// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Barbero struct {
	IDBarbero    int32  `json:"id_barbero"`
	Nombre       string `json:"nombre"`
	Apellido     string `json:"apellido"`
	Especialidad string `json:"especialidad"`
}

type Cliente struct {
	IDCliente int32  `json:"id_cliente"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
	Telefono  string `json:"telefono"`
	Email     string `json:"email"`
}

type Turno struct {
	IDTurno       int32     `json:"id_turno"`
	IDCliente     int32     `json:"id_cliente"`
	IDBarbero     int32     `json:"id_barbero"`
	Fechahora     time.Time `json:"fechahora"`
	Servicio      string    `json:"servicio"`
	Observaciones string    `json:"observaciones"`
}
